redhat-cop/openshift-playbooks

playbooks/AppDev/builds.adoc
Minor heading formatting and added new S2I reference
=> Minor formatting cleanup and added new S2I reference

README.adoc, playbooks/Installation/disconnected_environments.adoc
Added more comprehensive disconnected environment installation guidance from Erik Jacobs and Veer Muchandi
=> Enhanced disconnected environment installation guide

playbooks/Installation/logging_with_fluentd.adoc
-Fixed the formatting around "TD_AGENT_USER" and "TD_AGENT_GROUP" between lines 55 and 65
-Added logging config file for PaceMaker
-Added logging config file for Corosync
=> Fixed formatting, adding new logging sources

playbooks/Operationalizing/expose_docker_registry.adoc
Modified recommendations to use cluster edit role instead of cluster-admin role until newly created custom role recommendation task is complete
Also minor corrections to tls termination strategy and formatting
@etsauer please review
=> Updates and corrections to exposing registry doc

playbooks/Troubleshooting/Common-Issues.adoc, playbooks/Troubleshooting/README.adoc
Adding "Common Issues" to the Troubleshooting section to allow for capturing of issues found (and their workarounds) which aren't necessarily a bug. 
Read the "Common Issues" doc :smile_cat: 
N/A
/cc @etsauer @soggiest
=> Introducing "Common issues" as part of the Troubleshooting section

playbooks/troubleshooting/index.adoc, playbooks/troubleshooting/sti_jws.adoc
=> Troubleshooting Guide fixes

playbooks/app_dev/builds.adoc, playbooks/operationalizing/index.adoc, playbooks/operationalizing/integration.adoc
/cc @trevorquinn @oybed @sabre1041
=> Adding missing meta data, links, etc.

playbooks/installation/installation.adoc
=> Provided port definitions for Firewall rules

playbooks/installation/installation.adoc
re-submit for PR for Storage Option B
=> Provided Storage Option B

_layouts/default.html
=> Applying metadata changes for web site publishing

development_guide.adoc
@sabre1041 @trevorquinn Please review.
This PR adds a sample structure for contributing a demo.
=> Update to demo guide

_includes/google_analytics.html, _layouts/default.html
=> Adding google analytics reporting to playbooks website

README.adoc
Updated the README Contribution section to include guide for using Jekyll Asciidoc Docker container.
Follow Quickstart Guide using Docker instructions to validate that jekyll site was created and viewable. 
No
/cc @etsauer @sabre1041 @oybed
=> Quickstart docker

playbooks/installation/installation.adoc
I fat fingered the original :-(
=> Updated the port for Kubelet (10250) communication

development_guide.adoc, style_guide.adoc
=> Adding updates to development & style guides

playbooks/fundamentals/devops_reading_list.adoc, playbooks/fundamentals/index.adoc
This is a reading list & reference guide for DevOps topics
/cc @sabre1041 @JaredBurck @trevorquinn
=> Adding DevOps reference guide

_layouts/default.html, css/playbooks.css
Build playbooks site and examine.
@sabre1041
=> Disabling forced <h1> and adding Red Hat's Overpass font

script/cideploy.sh
Enabled PR testing in Travis and added additional check to ensure only `rhtconsulting` based project deploy to site
=> Added additional check to ensure only rhtconsulting builds are deployed

playbooks/operationalizing/cloudforms.adoc
Enhancements to the CloudForms documentation to resolve #77 
cc: @etsauer
=> Enhancements to CloudForms documentation

playbooks/fundamentals/docker_reference.adoc
Build playbooks, then view http://0.0.0.0:4000/playbooks/fundamentals/docker_reference.html
=> Adding OpenShift specific guidance to docker guide

playbooks/app_dev/builds.adoc, playbooks/installation/disconnected_environments.adoc, playbooks/installation/disconnected_satellite6.adoc
Updated various references/names to OSE images to resolve #91
=> Updates to OSE image references

playbooks/app_dev/binary_deployment_howto.adoc, playbooks/app_dev/index.adoc
cc @JaredBurck @sabre1041 @soggiest
=> Walk through of a binary deployment of ticket-monster to tomcat8

playbooks/installation/install_validation.adoc
=> Updates to CLI commands in the Validation Guide to be compatible with 3.2

playbooks/operationalizing/branding_console.adoc, playbooks/operationalizing/index.adoc
This is operationalization/branding_console playbook. Now, this doc has only manual configuration but I will also update ansible script url when it is ready.
Trello Card
https://trello.com/c/vDRWIM81/158-2-branding-console-login-page-web-console-template-2
=>  initial upload branding_console.adoc

playbooks/installation/installation.adoc
added additional packages to be installed
added a time section to ensure time is in sync
added section for company CA's to be installed
=> Added additional information regarding packages to be installed and running.  Addressed company CA's

playbooks/operationalizing/index.adoc, playbooks/operationalizing/ingress.adoc
Playbook for implementing ingress to expose services
https://trello.com/c/ha3ofR8S
/cc @etsauer @oybed
=> Added documentation on ingress functionality

.travis.yml
=> We want the build to report as failed if the site doesn't deploy.

script/cideploy.sh
@sabre1041 try this on for size
=> Making git config commands --global

playbooks/operationalizing/index.adoc
@sabre1041 @JaredBurck @dstockdreher
=> Linking out to image signing solution from red hat

playbooks/installation/install_validation.adoc, playbooks/operationalizing/index.adoc
=> Troubleshooting link

playbooks/app_dev/binary_deployment_howto.adoc, playbooks/app_dev/builds.adoc, playbooks/continuous_delivery/image_promotion.adoc, playbooks/fundamentals/devops_reading_list.adoc, playbooks/fundamentals/docker_reference.adoc, playbooks/installation/disconnected_environments.adoc, playbooks/installation/installation.adoc, playbooks/installation/ldap_integration.adoc, playbooks/installation/load_balancing.adoc, playbooks/installation/logging.adoc, playbooks/operationalizing/branding_console.adoc, playbooks/operationalizing/cloudforms.adoc, playbooks/operationalizing/expose_docker_registry.adoc
@sabre1041 @JaredBurck @mwitzenm
=> Adding a reminder to enable websockets on load balancers

playbooks/operationalizing/cloudforms_networking.adoc
Add haproxy configuration doing like F5. The haproxy in this doc stand for software load balancer in front of multiple masters. This configuration is verified by client.
=> Add haproxy configuration doing like F5

script/cideploy.sh
=> PR debug testing

README.adoc
addresses https://github.com/redhat-cop/openshift-playbooks/issues/130
Look at readme
https://github.com/redhat-cop/openshift-playbooks/issues/130
=> Fixing ruby version and repo link

docker/Dockerfile, docker/README.md, docker/bin/start.sh, docker/run.sh, playbooks/fundamentals/devops_reading_list.adoc
Migrate jekyll docker image to allow for testing content locally
Follow instructions in the README
https://trello.com/c/hFVeMAXO
cc: @redhat-cop/cant-contain-this @etsauer
=> Docker containiner for building playbooks

playbooks/operationalizing/cloudforms_networking.adoc, playbooks/operationalizing/custom_role_creation.adoc
Updates links to OpenShift documentation to reference the latest version
Verify links are active
https://trello.com/c/d4sjeyHM
https://github.com/redhat-cop/openshift-playbooks/issues/140
=> Updated links to reference latest documentation

playbooks/installation/index.adoc, style_guide.adoc
Updated style_guide.adoc to reflect correct callout tag
This is a PR to fix the callout at There's an INFO: callout at http://playbooks-rhtconsulting.rhcloud.com/playbooks/installation/#subscribing-directly-to-red-hat-2 that was not rendering.
Check the callout at http://playbooks-rhtconsulting.rhcloud.com/playbooks/installation/#subscribing-directly-to-red-hat-2 and verify that it is rendering correctly
#154 
=> Updated installation/index.adoc to fix callout

playbooks/operationalizing/index.adoc
When we published the new install guide, we bastardized a new guides. I'm adding a few links back under Operationalization with this PR
Check links in Operationalization
n/a
cc: @redhat-cop/cant-contain-this @raffaelespazzoli
=> Adding link to admin overview

playbooks/installation/index.adoc
Added a bit of missing info on the bootstrapping process for registry.
Read through bootstrap registry section of install guide.
n/a
=> Missed a few things during registry setup.

playbooks/fundamentals/devops_reading_list.adoc
Plain language definition for the CAMS Model for DevOps (Culture, Automation, Measurement, Sharing).
Click link
No.
=> CAMS Model Definition

playbooks/installation/index.adoc
Added a description of openshift_master_console_port, along with references in the inventory snippets, in the installation doc
Review all references of openshift_master_console_port for accuracy and confirm that it is not needed anywhere else
#159 
=> Added openshift_master_console_port to sample inventory snippets in installation/index.adoc

playbooks/installation/index.adoc, playbooks/installation/ldap_integration.adoc, playbooks/operationalizing/ldap_group_sync.adoc
Revises the LDAP integration delivery playbook by expanding the authentication section and breaking out the LDAP synchronization into its own delivery playbook to resolve #165 
Review the content
[GitHub](https://github.com/redhat-cop/openshift-playbooks/issues/165)
[Trello](https://trello.com/c/fgkdWQdK)
cc: @redhat-cop/cant-contain-this @redhat-cop/contributors
=> Added LDAP authentication and group synchronization guides

playbooks/installation/index.adoc
Added masters to Nodes host group in the install guide - ansible-inventory-update-4 section
Review the callout at http://playbooks-rhtconsulting.rhcloud.com/playbooks/installation/#ansible-inventory-update-4
#156 
=> Added masters to Nodes host group in the install guide - ansible-inventory-update-4 section

css/foundation.css, playbooks/installation/custom_certificates.adoc, playbooks/installation/index.adoc
Adds a guide to configuring custom certificates in OpenShift.
Read through new guide, and changes to install guide.
https://trello.com/c/r1Vj358a/5-1-custom-certificate-management-document
cc: @redhat-cop/cant-contain-this @timothyh
=> Custom certificates

playbooks/installation/admin_overview.adoc, playbooks/installation/index.adoc, playbooks/operationalizing/index.adoc, playbooks/operationalizing/monitoring_guide.adoc
Adds a monitoring guide with pointers to things to health check a cluster.
Build site, read through 0.0.0.0:4000/playbooks/operationalization/monitoring_guide.html
https://trello.com/c/QtSyTv0v/9-3-existing-monitoring
=> Adding monitoring guide starter

playbooks/operationalizing/integration.adoc
Brief explanation of the documentation or playbook changes you have made and/or the new content you are contributing.
Adding example / guidance on certificate auth with the api. 
Had to test this with case work for customer support issues. 
Provide a link to any open Github issues or Trello cards that describe the use case or problem you are solving.
No
cc: @etsauer  can you review (you were cc'ed in an email with @liggit and @deads)
=> providing an example on certificat auth with the api

playbooks/installation/index.adoc
Corrections to `subscription-manager` commands in install guide
Review changes
No
=> Corrections to subscription-manager commands in install guide

playbooks/troubleshooting/index.adoc
Adding in links for OCP 3.5 and 3.6 known issues
Build and view the page
N/A
=> Adding OCP 3.5 & 3.6 known issues links

playbooks/installation/index.adoc
Adding information on how to sync required images for OCP using Satellite.
The best way is probably to use the script in https://github.com/redhat-cop/openshift-toolkit/pull/21
and deploying a OCP cluster with the variables described.
None that I could find.
No preference.
=> add instructions for how to sync docker images with Satellite

container-images/local-builder/Dockerfile, container-images/local-builder/root/usr/local/bin/run, playbooks/fundamentals/devops_reading_list.adoc, playbooks/installation/admin_overview.adoc, playbooks/operationalizing/monitoring_guide.adoc
=> Several broken link fixes

playbooks/app_dev/index.adoc, playbooks/app_dev/properties-management.adoc
article on properties management
Standard review
not aware of
=> properties management

playbooks/troubleshooting/troubleshooting_guide.adoc
Adding to the troubleshooting guide.
Read doc.
n/a
=> Adding a builds section to the troubleshooting guide

.htaccess, .travis.yml, Gemfile, README.adoc, _layouts/default.html, build/dev/params, container-images/local-builder/Dockerfile, css/playbooks.css
Redirect old site to new site
n/a
cc: @sabre1041 @JaredBurck @rdebeasi
=> Redirecting playbooks site to uncontained domain

.travis.yml, Gemfile, README.adoc, container-images/local-builder/Dockerfile
Go back to 2.4.0
build local image, run pipeline
n/a
=> Going back to ruby 2.4.0

playbooks/troubleshooting/index.adoc
Updated with the latest troubleshooting articles and add OCP 3.7 known issues (release notes) to page.
Build and review the updated troubleshooting guide.
No issues or cards found.
=> added OCP 3.7 release notes and updates troubleshooting articles

playbooks/installation/index.adoc
fixed a link so the builds pass 
Ensure travis passes.
Run docker container.
=> Fixing a link so the build passes.

playbooks/fundamentals/devops_reading_list.adoc
=> Removing broken link

playbooks/operationalizing/secure-forward-splunk-container.adoc
Fix issues with failing builds
=> Fixed issue with duplicate ID's

Gemfile, playbooks/operationalizing/secure-forward-splunk-container.adoc
(hopefully) this will fix our pipeline.
Repoint build to branch temporarily
n/a
=> Fixing build dependency and small doc error

playbooks/installation/ldap_integration.adoc
Very tricky bug in scope parsing. 
https://tools.ietf.org/html/rfc2255
Brief explanation of the documentation or playbook changes you have made and/or the new content you are contributing.
Provide a link to any open Github issues or Trello cards that describe the use case or problem you are solving.
=> Fix LDAP filter URI

build/template.yml, inventory-dev/group_vars/all.yml, inventory-dev/hosts, inventory-prod/group_vars/all.yml, inventory-prod/hosts, pipeline.md, policy/rolebindings.yml, policy/serviceaccounts.yml
Make our pipeline "apply-able".
Review test new steps in `pipeline.md`.
https://trello.com/c/hw1YQ9Ci/81-make-uncontained-playbooks-pipeline-applyable
cc: @redhat-cop/cant-contain-this @sherl0cks
=> Adding initial version of an applier inventory for IaC of the pipeline

playbooks/continuous_delivery/external-docker-registry-integration.adoc
Enhanced documentation around integration with external docker registries to provide additional clarity on the configuration of secrets
Review modifications
https://github.com/redhat-cop/openshift-playbooks/issues/214
cc: @redhat-cop/cant-contain-this @etsauer
=> Enhanced external docker integration and updated broken links

playbooks/installation/load_balancing.adoc
Brief explanation of the documentation or playbook changes you have made and/or the new content you are contributing.
Fix incorrect statement around websockets and Amazon ELB's.  As of 2016 ELB's support websockets.  https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/
Read above link and confirm.
Provide a link to any open Github issues or Trello cards that describe the use case or problem you are solving.
No Trello card.
cc: @redhat-cop/cant-contain-this @etsauer @JaredBurck @sbre1041
=> Update load balancing guide to remove incorrect statement around Amazon on ELB and websockets

playbooks/operationalizing/custom_role_creation.adoc
Fix typos in the "creating a custom role" section of the documentation.
No testing necessary.  Visually confirm.
Not to my knowledge.
Anyone with necessary perms.
=> Fix typos in the "creating a custom role" section of the documentation.

playbooks/installation/index.adoc
Add some commentary around the Network Sizing a the host length bits
Review language
https://trello.com/c/VddVZeP9/108-introduction-and-fundamentals-on-the-sdn-cidr-and-sizing-for-openshift
=> Add some commentary around Network Sizing and the math behind it

playbooks/fundamentals/docker_reference.adoc, playbooks/fundamentals/index.adoc, playbooks/troubleshooting/index.adoc
Updated troubleshooting index.adoc page to have more context for each section and links so users can find the specific troubleshooting guidance they may be looking for.  Additionally updated content and context similarly for container fundamentals.
Build site and review the updated pages for context and content.  Please provide feedback on content.
GitHub issue #261  and Trello [card](https://trello.com/c/Q78GNpMz/83-add-contextual-information-around-the-troubleshooting-links-index) 
cc: @redhat-cop/cant-contain-this  @mwitzenm
=> Troubleshooting

playbooks/fundamentals/index.adoc, playbooks/fundamentals/template_development_guide.adoc
Beginnings of a Template development guide. This should not be merged yet.
Read through new document and provide feedback
cc: @redhat-cop/cant-contain-this, specifically @sabre1041 @oybed @pabrahamsson
=> Template Development Guide

playbooks/fundamentals/index.adoc
"Getting started with OpenShift cli"
Adds link to "oc command for newbies" blog post in fundamental index.
Just review link name and order in the index .
https://trello.com/c/uXq7u8b9/110-getting-started-with-the-openshift-cli
=> Adds link to "oc command for newbies" blog post in fundamental index.

playbooks/fundamentals/index.adoc
This PR is follow-up for DNS Deep Dive #221
@JaredBurck  I add the link to fundamental index.adoc under reading list.
https://trello.com/c/watsufdo/76-dns-deep-dive-in-openshift-36
=> Add DNS Deep Dive link to fundamental index.adoc

.travis.yml, Gemfile, container-images/local-builder/Dockerfile, inventory-dev/group_vars/all.yml, inventory-dev/hosts
Should fix the broken pipeline
- Make sure CI passes. 
- Build local builder image: `cd container-images/local-builder && docker build -t redhatcop/jekyll-local-builder:latest .`
- Ensure local-builder image still works. `cd openshift-playbooks && docker run   -u `id -u` -it   -v $PWD/:/home/jekyll/src/:Z   -p 4000:4000   redhatcop/jekyll-local-builder`
=> Making some changes to update version of ruby and make pipeline work

Jenkinsfile
Removes the slash from APP_NAME
Run the pipeline.
n/a
=> Fix APP_NAME in Jenkinsfile

Jenkinsfile
This fixed promotion slave issue where the pod crashes due to no protocol found
run pipeline
n/a 
=> Promotion slave update

playbooks/troubleshooting/index.adoc, playbooks/troubleshooting/troubleshooting_guide.adoc
Brief explanation of the documentation or playbook changes you have made and/or the new content you are contributing.
Provide a link to any open Github issues or Trello cards that describe the use case or problem you are solving.
=> Updated known issues links to include 3.9

playbooks/continuous_delivery/image_promotion.adoc
Add brief introduction and example of image promotion using skopeo
Just documentation, let me know if I got it wrong
#277 
=> Added information about image promotion with skopeo (#277)

playbooks/continuous_delivery/external-docker-registry-integration.adoc
Small correction to where to store custom docker certificates
Review changes
No
=> Adding port to external docker registry document

playbooks/app_dev/APM_guidance.adoc, playbooks/fundamentals/devops_reading_list.adoc, playbooks/installation/logging_with_fluentd.adoc, playbooks/operationalizing/secure-forward-splunk-container.adoc, playbooks/operationalizing/secure-forward-splunk.adoc
Fix broken links identified by the html link checker.
Run the jekyll build and the html proofer in the Jenkins file. 
https://github.com/redhat-cop/openshift-playbooks/issues/301
=> WIP - Fix broken links in build. #301
