redhat-cop/openshift-playbooks

- playbooks/app_dev/builds.adoc
Documentation on placing binary content in deployments folder for S2I builds to resolve #18
> Additional documentation on binary deployments

- playbooks/app_dev/binary_deployment_howto.adoc
- playbooks/app_dev/builds.adoc
- playbooks/continuous_delivery/image_promotion.adoc
- playbooks/fundamentals/devops_reading_list.adoc
- playbooks/fundamentals/docker_reference.adoc
- playbooks/installation/disconnected_environments.adoc
- playbooks/installation/installation.adoc
- playbooks/installation/ldap_integration.adoc
- playbooks/installation/load_balancing.adoc
- playbooks/installation/logging.adoc
- playbooks/operationalizing/branding_console.adoc
- playbooks/operationalizing/expose_docker_registry.adoc
Fixed broken external links to resolve build failure.  Also updated docs.openshift.com URLs from `/enterprise/{version}/` to `/container-platform/latest/` in order to reduce link maintenance.
> Resolve broken external links build failure

- script/cideploy.sh
removed `rhtconsulting/openshift-playbooks` and replaced with `redhat-cop/openshift-playbooks`
this will help to prevent future issues and uses the migrated repo name.
@etsauer @sabre1041
> Updated value for Travis Repo Slug

- playbooks/installation/index.adoc
Includes link to [OpenShift Artifactory reference architecture](https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/jfrog_artifactory_on_openshift_container_platform/) in install guide
Review change
https://trello.com/c/IHenQ7Tt
https://github.com/redhat-cop/openshift-playbooks/issues/146
> Added reference to Artifactory reference architecture

- playbooks/installation/index.adoc
Updated LVM commands to avoid conflicts between nodes and etcd when etcd is hosted on nodes.
N/A
N/A
> Updating LVM comands to avoid conflict with etcd/nodes

- README.adoc
Removed the callout on the index page to modify the location of the source code path in the `docker-compose.yml` file. By default, the location references the current directory
Review changes
No
> Removed note regarding src path

- playbooks/operationalizing/secure-forward-splunk.adoc
base64 should be given the -w 0 (non-wrap) option to ensure the encoded certificate does not contain a newline character.
> Update base64 usage doc in secure-forward-splunk.adoc

- playbooks/operationalizing/secure-forward-splunk.adoc
Fixed typo in secure-forward-splunk.adoc.
> Fix typo: Privae => Private

- playbooks/operationalizing/secure-forward-splunk.adoc
Updates the configuration based on the latest documentation for the ConfigMap used for Secure Forward Plugin
Review the changes and compare with latest [OpenShift documentation](https://docs.openshift.com/container-platform/3.6/install_config/aggregate_logging.html#sending-logs-to-an-external-elasticsearch-instance)
No
cc: @redhat-cop/cant-contain-this @etsauer @cpitman @JaredBurck
> Add <store> tags to secure forward configmap

- playbooks/installation/index.adoc
Routers have a built in health check on port 1936. This modifies the example scripts for F5 and Citrix LBs to use the health check instead of TCP monitors on ports 80 and 443.
To actually verify these changes someone would need to have access to BigIP and NetScaler devices. These edits were written based on the documentation for the devices.
> Modify LB Setup to Use Router Health Check

- playbooks/installation/index.adoc
Masters have a healthcheck endpoint at `/healthz`, this adds that URI for load balancer configuration of Citrix NetScaler and F5 BigIP devices.
Like the previous PR, I cannot test these changes. The syntax was pulled from the device manuals.
> Configre LBs for Master Healthcheck

- playbooks/operationalizing/branding_console.adoc
After ansible playbooks are merged to openshift-toolkit, the branding_console doc need to add those links.
This is simple link update so I believe that clicking those links are enough to review
Nope
> Branding_console add ansible playbook links 

- .travis.yml
- playbooks/installation/admin_overview.adoc
- playbooks/operationalizing/cloudforms_networking.adoc
- script/cibuild.sh
updated the 404 broken links found by `html proofer`.  updated the travis config file to improve builds. And added `--only-4xx` flag to `html proofer` command in order to only throw an error when it hits an error message in the 400-499 range.
verify the travis build is successful with no link errors.
no
cc: @redhat-cop/cant-contain-this @etsauer @sabre1041
> Fix for travis-ci htmlproofer broken build

- Jenkinsfile
- script/cibuild.sh
Added the `--only-4xx` flag in the Jenkinsfile for htmlproofer to only throw an error when it hits an error message in the 400-499 range.
Build the website using the Jenkinsfile and verify that the build is successful. 
no. adds same fix as PR #220 
cc: @redhat-cop/cant-contain-this @etsauer
> add --only-4xx flag for htmlproofer

- playbooks/operationalizing/branding_console.adoc
The playbooks for branding console are moved to under branding folder (openshift-toolkit repo) so the link in the doc should be updated. Now it is broken.
Click links
#231
> Change the link for ansible script

- deploy/template.yml
Our production site runs under a tight quota, so I'm adding resource limits to make room for more pods.
Deploy app, see that there are now resource limits in place.
```
oc process -f deploy/template.yml --param-file deploy/dev/params | oc apply -f -
```
n/a
> Adding memory parameters to deployment configs

- playbooks/installation/index.adoc
Still listed the 3.6 rpms while rest of document references 3.7
Typo in repo command
Should be obvious :)
no
> Replace rhel-7-server-ose-3.6-rpms with rhel-7-server-ose-3.7-rpms

- playbooks/installation/index.adoc
Fix a minor error with the subscription-manager command on line 833 as it is missing an ending quote.
Verify the updated command.
No, found the issue while working with a client.
cc: @redhat-cop/cant-contain-this @sabre1041 @etsauer
> Add missing ending single quote on subscription-manager command

- playbooks/continuous_delivery/external-jenkins-integration.adoc
The Openshift Sync plugin bundled with the latest Jenkins needs specific versions of particular BlueOcean plugins in order to work. I've updated the External Jenkins documentation to reflect this fact. 
I've also explicitly spelled out how the JLNP ports should be provided.
- Download the latest Jenkins.
- Attempt to setup and test a sample external Jenkins pipeline *without* downgrading the BlueOcean plugins.
- The pipeline will throw an exception and fail to execute.
- Downgrade the plugins as per the PR and execute the pipeline again, it will succeed.
No.
@etsauer
> Updated versions for plugins that the Openshift Sync Plugin depends on for External Jenkins Integration

- playbooks/operationalizing/secure-forward-splunk-container.adoc
Adds the <store> tags around the secure forward configuration, so that other stores don't get clobbered(e.g., OpenShift's own Elasticsearch).
On an existing cluster with EFK already deployed, then deploy with this configmap. Logs should ship to both stores.
Also see #193 
No.
> Add the <store> tags around the secure forward config.
